# Generated by Django 3.1.4 on 2020-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='description', max_length=250)),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='book_covers')),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
        ),
    ]
